### ISSUE TITLE
Many WARNs, How to fix them?

### ISSUE THREAD

**Issue by IAmNotGEM** [xsun2001/Applied-Energistics-2-Unofficial#15] opened 2017-12-28 15:29 UTC
[23:25:07] [Server thread/INFO]: Starting AE2 CSV Export
[23:25:07] [AE2 CSV Export/INFO]: Cache is enabled. Checking for new mod configurations.
[23:25:07] [AE2 CSV Export/INFO]: New mod configuration was found. Commencing exporting.
[23:25:07] [AE2 CSV Export/INFO]: Item Exporting ( started )
[23:25:07] [AE2 CSV Export/WARN]: Exception in thread "AE2 CSV Export" 
[23:25:07] [AE2 CSV Export/WARN]: java.lang.NoSuchMethodError: net.minecraft.item.Item.func_77640_w()Lnet/minecraft/creativetab/CreativeTabs;
[23:25:07] [AE2 CSV Export/WARN]: 	at appeng.services.export.MinecraftItemCSVExporter$ItemRowExtractFunction.apply(MinecraftItemCSVExporter.java:229)
[23:25:07] [AE2 CSV Export/WARN]: 	at appeng.services.export.MinecraftItemCSVExporter$ItemRowExtractFunction.apply(MinecraftItemCSVExporter.java:185)
[23:25:07] [AE2 CSV Export/WARN]: 	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:582)
[23:25:07] [AE2 CSV Export/WARN]: 	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
[23:25:07] [AE2 CSV Export/WARN]: 	at com.google.common.base.Joiner$2.appendTo(Joiner.java:253)
[23:25:07] [AE2 CSV Export/WARN]: 	at com.google.common.base.Joiner.appendTo(Joiner.java:152)
[23:25:07] [AE2 CSV Export/WARN]: 	at com.google.common.base.Joiner.join(Joiner.java:193)
[23:25:07] [AE2 CSV Export/WARN]: 	at com.google.common.base.Joiner.join(Joiner.java:183)
[23:25:07] [AE2 CSV Export/WARN]: 	at appeng.services.export.MinecraftItemCSVExporter.export(MinecraftItemCSVExporter.java:90)
[23:25:07] [AE2 CSV Export/WARN]: 	at appeng.services.export.ExportProcess.run(ExportProcess.java:123)
[23:25:07] [AE2 CSV Export/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by xsun2001** [comment] 2018-02-16 11:18
I'm sorry to keep you waiting SO long. But I cannot reproduce this issue in my own environment. Please confirm your forge version and AE2 version again. I will close this issue and reopen it when it can be reproduced.

**Closed as completed by xsun2001** 2018-02-16 11:18 UTC
Labels: cannot reproduce

**Comment by thiago-solfo** [comment] 2023-08-22 11:14
I know it's been a while but this might help other people still playing on 1.7.10.

This error only happens on **dedicated servers**; In single player works normally.

The "Facades.cfg" file is always empty and and the "items.csv" file generation fails.

Maybe something on [MinecraftItemCSVExporter.java](https://github.com/xsun2001/Applied-Energistics-2-Unofficial/blob/rv3-1.7.10/src/main/java/appeng/services/export/MinecraftItemCSVExporter.java#L229) is wrong?

```
[AE2 CSV Export/INFO] [AE2:C]: Item Exporting ( started )

Exception in thread "AE2 CSV Export" [AE2 CSV Export/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoSuchMethodError: net.minecraft.item.Item.func_77640_w()Lnet/minecraft/creativetab/CreativeTabs;

[AE2 CSV Export/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at appeng.services.export.MinecraftItemCSVExporter$ItemRowExtractFunction.apply(MinecraftItemCSVExporter.java:237)
[AE2 CSV Export/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at appeng.services.export.MinecraftItemCSVExporter$ItemRowExtractFunction.apply(MinecraftItemCSVExporter.java:193)
[AE2 CSV Export/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:582)
[AE2 CSV Export/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
[AE2 CSV Export/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at com.google.common.base.Joiner$2.appendTo(Joiner.java:253)
[AE2 CSV Export/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at com.google.common.base.Joiner.appendTo(Joiner.java:152)
[AE2 CSV Export/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at com.google.common.base.Joiner.join(Joiner.java:193)
[AE2 CSV Export/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at com.google.common.base.Joiner.join(Joiner.java:183)
[AE2 CSV Export/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at appeng.services.export.MinecraftItemCSVExporter.export(MinecraftItemCSVExporter.java:99)
[AE2 CSV Export/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at appeng.services.export.ExportProcess.run(ExportProcess.java:126)
[AE2 CSV Export/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at java.lang.Thread.run(Unknown Source)
```
> "Facades.cfg" empty and "items.csv" absent.
![image](https://github.com/xsun2001/Applied-Energistics-2-Unofficial/assets/61445366/999b76de-c0d3-47a9-b45d-383fcf10276d)

- In essence, the bug **prevents the "Facades.cfg" file from working** and it also **prevents new facades from being enabled** (if it is already in the file) on dedicated servers.

_looks like i won't be able to cover the ground with thaumcraft's greatwood planks facade :(_

## Files
- Applied Energistics: appliedenergistics2-rv3-beta-6.jar
- FML: forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
- Java: jre1.8.0_202

@xsun2001 is it now possible to reproduce? I spent 6 hours running 11 total tests on my modpack until I came to this conclusion
