### ISSUE TITLE
Crafting Terminal throwout 

### ISSUE THREAD

**Issue by DrKilledalot** [xsun2001/Applied-Energistics-2-Unofficial#13] opened 2017-09-19 13:11 UTC
![pic1](https://user-images.githubusercontent.com/30718202/30596053-5552946c-9d53-11e7-8cdc-d0800c7f09da.PNG)
So , im playing the divine journey modpack version 1.5.2 with projecte and equivalent energistics and aromas mining world added
I also replaced the old official rv3 .6 version with the newest .13 version , and while it did not lead to compability issues with other addons , it did not eliminate the bug i had before with the .6 version so iam reporting this:

I have my main ae2 system setup in a forcfully loaded chunk in the mining dimension , and connected it with a quantum ring to my acess terminals and buses in the overworld , but after setting up my thaumcraft area the terminal i connected just throws me out of the interface without any errors when i try to autocraft smth  (the items dont get crafted either since no confimation windows pops up) 
So after a few hours of testing around , this seems to occur at about ~27 blocks away from the quantum ring ,  both when connected via another ring or cable (and no its not a power issue already tried adding 8 dense cells) Also ervything in the overworld connected to the ae network is focfully chunkloaded too

(on the pic the left pannel works for autocrafting with 26 blocks distance to the ring the right one does not , all buses and interfaces still work perfectly fine)
Unfortunatly , i cant get to replicate itself

**Comment by xsun2001** [comment] 2017-09-20 05:40
Errr... Sorry for my poor English but I have to ask a few questions to undertand you better. It seems that your ae system cannot autocraft with the distance more than 26 blocks from quantum ring, right? Is your auto craft system such as crafting cpus in the overworld network or in the mining dimension connected by quantum ring? Is there enough channels left in the network?(Well... It is online so the channel may be ok...) Did you test it in another world? 
Sorry for those too many questions but it is not convinence for me to open my computer to test it. I will look at it in the later time today.

**Comment by xsun2001** [comment] 2017-09-20 12:41
If I didn't misunderstand you, I have to say sorry because I cannot reproduce this issue on my computer.
The Overworld
![2017-09-20_20 34 54](https://user-images.githubusercontent.com/14010993/30644001-82ea9cbc-9e43-11e7-84b4-581904f5c324.png)
You can see the quantum ring which connected to another ring in the Nether and a ME terminal with >30 blocks distance. But it worked fine as usual and it can craft items.

The Nether
![2017-09-20_20 35 05](https://user-images.githubusercontent.com/14010993/30644094-d54d5e04-9e43-11e7-938a-23f0942fd84b.png)
I build a very simple auto craft system and you can understand it easily.

So please tell me more detail and help me to reproduce the issue. I will try to solve your problem.

**Comment by DrKilledalot** [comment] 2017-09-21 00:07
Yes except for a few buses interfaces and terminals evrything else is in the mining dimension in one chunk
 
In terms of the 27 block range until it throws me out of the terminal ; i also have another connection ~33 blocks away and tested it there , it worked , the only difference between the working one and the failing one was in which direction they were away from the quantum ring

My entire setup is a bit difficult to show exactly with screenshots , so i made this little streamable video where i just show the distance of the terminals that throw me out when i try to autocraft and the ones that dont ,aswell as my network in my work-cunk
https://streamable.com/pqe80


Even stranger since last time i tested it , the range seems to have gotten ~2 blocks shorter , which probably means it  varies each session :/
(btw. using either cables , the quantum ring, or ae2 stuff`s wireless cable yilds the same results)
And yes i tried to reproduce it in another world and didnt suceed

**Comment by xsun2001** [comment] 2017-09-21 05:33
Thank you for your patience test and now I can compeletly understand you. I will go inside the code and find out the problem tomorrow because I cannot use my computer today.(Studyyyyyy......) But if you have the method to reproduce it, it must be much more helpful for me to deal with it.

> A bug which is random and cannot reproduce is the most troublesome...

**Comment by DrKilledalot** [comment] 2017-09-21 20:18
If you want i can give you my world save so you can investigate this a bit better
be warned tough this modpack takes ages to load up

**Comment by xsun2001** [comment] 2017-09-29 15:03
Ohhh,,, Sorry for those days' delay. It may not be useful because I cannot setup my dev env with so many mods, and most of them hasn't a dev version. And if I can get your email address, we can have a closer communication with each other. I will close this issue and it will be reopened if there are more examples of the bug or it can be reproduced in my computer. I'm sorry for that I cannot solve this problem due to my incompetent.

**Closed as completed by xsun2001** 2017-09-29 15:03 UTC
Labels: cannot reproduce

**Comment by DrKilledalot** [comment] 2017-10-02 14:33
dont worry you arent incompotent :) , ill try myself to get it reproduced and tell ya if i can

tough when putting my world in a pack that only has ae2 , aromas mining world , and the ae2 addons
i dont get it to throw me out
